
CREATE DATABASE esquema_inicio_sesion;

USE esquema_inicio_sesion;

CREATE TABLE usuarios(
id_usuario INT PRIMARY KEY NOT NULL UNIQUE,
nombre VARCHAR(200) NOT NULL,
apellido VARCHAR(200) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(200) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

