-- MySQL Script generated by MySQL Workbench
-- Tue May 19 12:14:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_mensajes` DEFAULT CHARACTER SET utf8 ;
USE `sistema_mensajes` ;

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`tipo_usuarios` (
    `id_tipo_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `nombre_tipo_usuario` VARCHAR(45) NOT NULL,
    `descripcion_tipo_usuario` VARCHAR(45) NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP, -- Current_timestamp
    `update_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_by` INT NULL,
    `delete` TINYINT(1) DEFAULT 0,
    PRIMARY KEY (`id_tipo_usuario`),
    UNIQUE INDEX `id_tipo_usuarios_UNIQUE` (`id_tipo_usuario` ASC) VISIBLE)
ENGINE = InnoDB;

-- diego muere- debemos sacarlo del sistema. borrado logico fisico from usuario
-- con delete el dato deja de existir - no se puede recuperar
-- en cambio con borrado logico  (campo deleted activo - deleted 1)
-- podemos ocultar el usuario para que el cliente no lo vea
-- pero no sale del sistema


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`usuarios` (
    `id_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(100) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `password_hash` VARCHAR(255) NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_by` INT NULL,
    `delete` TINYINT(1) DEFAULT 0, -- Borrado logico - No se borar el elemento o el registro fisicamente 
    `id_tipo_usuario` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`id_usuario`),
    UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
    UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
    INDEX `fk_usuarios_tipo_usuarios_idx` (`id_tipo_usuario` ASC) VISIBLE,
    CONSTRAINT `fk_usuarios_tipo_usuarios`
        FOREIGN KEY (`id_tipo_usuario`)
        REFERENCES `sistema_mensajes`.`tipo_usuarios` (`id_tipo_usuario`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`mensajes` (
    `id_mensaje` INT NOT NULL AUTO_INCREMENT,
    `contenido` TEXT NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_by` INT NULL,
    `delete` TINYINT(1) DEFAULT 0,
    `emisor` INT UNSIGNED NOT NULL,
    `receptor` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`id_mensaje`),
    INDEX `fk_mensajes_usuarios1_idx` (`emisor` ASC) VISIBLE,
    INDEX `fk_mensajes_usuarios2_idx` (`receptor` ASC) VISIBLE,
    CONSTRAINT `fk_mensajes_usuarios1`
    FOREIGN KEY (`emisor`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_mensajes_usuarios2`
    FOREIGN KEY (`receptor`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`comentarios` (
    `id_comentario` INT NOT NULL AUTO_INCREMENT,
    `contenido` TEXT NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_by` INT NULL,
    `delete` TINYINT(1) DEFAULT 0,
    `id_usuario` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`id_comentario`),
    INDEX `fk_comentarios_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
    CONSTRAINT `fk_comentarios_usuarios1`
        FOREIGN KEY (`id_usuario`)
        REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Insertar Datos de tablas 
USE sistema_mensajes;

INSERT INTO tipo_usuarios(nombre_tipo_usuario, descripcion_tipo_usuario)

VALUES (
    "Administrador",  "Administra todo",
    "Usuario", "Solo puede interactuar",
    "Usuario", "Solo puede interactuar",
    "Usuario", "Solo puede interactuar",
    "Usuario", "Solo puede interactuar"
)



INSERT INTO usuarios(username, email, password_hash)

VALUES (
    "Benjamin", "benja@gmailcom", "benja123"
)



